name: Zola on GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
        with:
          submodules: 'true'
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
        with:
          submodules: 'true'
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
